project_name: xray

version: 2

builds:
  - id: main
    env:
      - GOEXPERIMENT=greenteagc,jsonv2
      - CGO_ENABLED=0
    flags:
      - -v
      - -trimpath
    ldflags:
      - -X github.com/xtls/xray-core/core.build={{.Version}}
      - -s
      - -w
      - -buildid=
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v3
      - v2
      - v1
    main: ./main
    binary: xray

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-{{ .Amd64 }}"
    formats:
      - tar.gz
